import Link from "next/link";

// const FEEDBACK_EMAIL = "yuri.olivares0608@gmail.com";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="border-t border-border py-6">
      <h2 className="text-[15px] font-medium text-text-primary">{title}</h2>
      <div className="mt-2 flex flex-col gap-2 text-[15px] text-text-secondary">{children}</div>
    </section>
  );
}

export default function AboutPage() {
  return (
    <div className="mx-auto w-full max-w-3xl flex-1 px-6 py-10">
      <h1 className="text-[26px] font-semibold text-text-primary">About</h1>
      <p className="mt-1 text-[15px] text-text-secondary">pre, May Reviewer ka ba?</p>

      <div className="mt-6 flex flex-col">
        <Section title="What this is">
          <p>
            May Reviewer turns your notes, handouts, and project material into a practice quiz you
            can retake as often as you want. Still shaped around the exam it was built for — see 
            Known limitations below
          </p>
        </Section>

        <Section title="How it works">
          <p>
            You describe a subject and its topics, paste or upload your material, and questions are
            generated by Google&apos;s Gemini model (<span className="font-mono">gemini-3.1-flash-lite</span>).
          </p>
          <p>
            Your reviewers, questions, and quiz history live in this browser only. Nothing is kept
            on a server and nothing is shared between devices. Clearing your browser data deletes
            them. Uploaded material is sent out once, during generation, so the model can read it:
            text files are read in the browser and sent as text, while PDFs are uploaded to
            temporary storage, read by the model, then deleted right after the questions come back.
            No third parties beyond that are involved, and nothing is used for training or
            advertising.
          </p>
        </Section>

        <Section title="Known limitations">
          <ul className="flex list-disc flex-col gap-1.5 pl-5">
            <li>
              Only one reviewer format exists: four fixed question types (Identification, Scenario,
              Timeline, Code) tailored to a specific exam format. It&apos;s not general-purpose yet.
            </li>
            <li>
              Question quality depends entirely on the material you upload. Thin or unfocused source
              material produces thin questions, and the model can still get things wrong.
            </li>
            <li>No accounts, no multi-user, no collaboration. Sharing happens through Import/Export.</li>
            <li>
              Uploads accept <span className="font-mono">.pdf</span>,{" "}
              <span className="font-mono">.docx</span>, <span className="font-mono">.txt</span>, and{" "}
              <span className="font-mono">.cpp</span>. Up to 10 files per field, 15 MB each and 40
              MB in total.
            </li>
            <li>
              Generation is rate limited to 8 runs every 10 minutes to keep model costs in check.
            </li>
          </ul>
        </Section>

        <Section title="What's next">
          <p>Nothing here is promised, but these are the likely directions:</p>
          <ul className="flex list-disc flex-col gap-1.5 pl-5">
            <li>Custom question types and reviewer formats beyond the current four.</li>
            <li>Accounts, so reviewers aren't stuck in one browser. Sign in, and you can see your reviewers across devices.</li>
            <li>An actual database (likely Supabase) to back that, instead of everything living in IndexedDB.</li>
            <li>A page for browsing reviewers other people have made and installing one into your own account, 
                with the option to keep the underlying source files private and only share the generated questions.</li>
            <li>Better handling of longer or image-heavy source material: this one costs more per generation, 
                so it depends on how the free tier holds up once more people are using it.</li>
          </ul>
        </Section>

        {/* <Section title="Feedback">
          <p>
            Found a bug or have a suggestion?{" "}
            <a
              href={`mailto:${FEEDBACK_EMAIL}?subject=May%20Reviewer%20feedback`}
              className="font-medium text-accent underline"
            >
              Send feedback
            </a>
            .
          </p>
        </Section> */}

        <Section title="Credits">
          <p>
            Question generation is powered by Google Gemini. Built with Next.js, React, and Tailwind
            CSS, with <span className="font-mono">mammoth</span> for reading{" "}
            <span className="font-mono">.docx</span> files,{" "}
            <span className="font-mono">fflate</span> for zip import/export, and{" "}
            <span className="font-mono">idb</span> for storing uploaded files in the browser.
          </p>
        </Section>

        <section className="border-t border-border py-6">
          <h2 className="text-[15px] font-medium text-text-primary">Disclaimer</h2>
          <p className="mt-2 text-[14px] text-text-tertiary">
            This is an independent personal project, not affiliated with or endorsed by any school,
            course, or instructor. Generated questions are practice material only. They&apos;re not
            guaranteed to be accurate and are not official exam content. Always check your own
            source material and verify the generated questions and answers before using them for 
            studying or sharing them with others.
          </p>
        </section>
      </div>
    </div>
  );
}
