function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="border-t border-border py-6">
      <h2 className="text-[15px] font-medium text-text-primary">{title}</h2>
      <div className="mt-2 flex flex-col gap-2 text-[15px] text-text-secondary">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="mx-auto w-full max-w-3xl flex-1 px-6 py-10">
      <h1 className="text-[26px] font-semibold text-text-primary">Terms of Use</h1>
      <p className="mt-1 text-[15px] text-text-secondary">Last updated September 12, 2026.</p>

      <div className="mt-6 flex flex-col">
        <Section title="What this is">
          <p>
            May Reviewer is a free personal study tool that turns your notes and material
            into practice questions. It is an independent personal project, not affiliated
            with or endorsed by any school, course, or instructor.
          </p>
        </Section>

        <Section title="AI-generated content">
          <p>
            Questions are generated by an AI model and can be wrong. They are practice
            material only — not official exam content, and not guaranteed accurate. Always
            check generated questions and answers against your own source material before
            studying from them or sharing them with others.
          </p>
        </Section>

        <Section title="Your content">
          <p>
            Your notes, files, and reviewers stay yours. The app claims no ownership over
            anything you upload or create. Only upload material you have the right to use
            for studying.
          </p>
        </Section>

        <Section title="Fair use">
          <ul className="flex list-disc flex-col gap-1.5 pl-5">
            <li>Use the app for studying and normal practice.</li>
            <li>Don&apos;t work around the rate limits or upload caps.</li>
            <li>Don&apos;t upload unlawful content or other people&apos;s private material.</li>
          </ul>
        </Section>

        <Section title="No warranty">
          <p>
            The app is provided as-is, without warranties of any kind. To the extent
            permitted by law, the developer is not liable for any loss arising from your
            use of the app, including from inaccurate generated questions.
          </p>
        </Section>

        <Section title="Changes">
          <p>
            These terms may change as the app grows (accounts and sync are on the roadmap).
            Material changes will be noted here with a new date.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about these terms:{" "}
            <a href="mailto:support@example.com?subject=May%20Reviewer%20terms" className="font-medium text-accent underline">
              support@example.com
            </a>
            .
          </p>
        </Section>
      </div>
    </div>
  );
}
